# Site settings
title: A DB Guy
email: myname@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hi. This is the homepage of lgylym.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://lgylym.github.io" # the base hostname & protocol for your site
twitter_username: lgylym
github_username:  lgylym

# Build settings
markdown: kramdown
